# Generated by Django 5.2.7 on 2025-11-14 07:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_class_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='subject',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
