# Generated by Django 5.2.7 on 2025-11-22 11:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_assignmentsubmission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assignment_submissions',
            field=models.ManyToManyField(related_name='assignments_submitted', through='core.AssignmentSubmission', to=settings.AUTH_USER_MODEL),
        ),
    ]
